# docker-compose.yaml

services:
  postgres:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yalla
      - POSTGRES_DB=property_data
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - sql-agent-network
networks:
  sql-agent-network:
    external: true